updates -> colemak3.zip colemak4.zip colemak_caps_to_esc.zip colemak_caps_to_esc2.zip ...

diff --git a/git_templates/hooks/pre-commit b/git_templates/hooks/pre-commit
--- a/git_templates/hooks/pre-commit
+++ b/git_templates/hooks/pre-commit
@@ -3,17 +3,17 @@
 #  Author:  Jose Lima
 #  Date:    2024-01-03 15:25
 
-if [ -d "tests/" ]; then
-  python3 -m pytest tests/ -v
-  RET=$?
-elif [ -d "priv/" ]; then
-  python3 -m pytest priv/ -v
-  RET=$?
-fi
+# if [ -d "tests/" ]; then
+#   python3 -m pytest tests/ -v
+#   RET=$?
+# elif [ -d "priv/" ]; then
+#   python3 -m pytest priv/ -v
+#   RET=$?
+# fi
 
-if [ $RET -ne 0 ]; then
-  echo "pytest failed"
-  exit 1
-fi
+# if [ $RET -ne 0 ]; then
+#   echo "pytest failed"
+#   exit 1
+# fi
 
-exit 0
+# exit 0
