updates -> nvim/lua/plugins/theme_catppuccin.lua zshrc_mac

diff --git a/zshrc_mac b/zshrc_mac
--- a/zshrc_mac
+++ b/zshrc_mac
@@ -58,9 +58,9 @@ ta () {
 }
 
 # lets go right to businees
-if [ -n $SSH_TTY ]; then
-  command -v tmux &> /dev/null && ta || echo "tmux not found..."
-fi
+# if [ -n $SSH_TTY ]; then
+#   command -v tmux &> /dev/null && ta || echo "tmux not found..."
+# fi
 
 typeset -U path
 
